### PR TITLE
chore: add nakama beta key option to world toml

### PR DESCRIPTION
**Pull request by zulkhair**
Closes: WORLD-726

## Overview
Expose `ENABLE_ALLOWLIST` env variable through world.toml

## Brief Changelog
- add `ENABLE_ALLOWLIST` to nakama docker env
- add `ENABLE_ALLOWLIST` field to world.toml

### CODE REVIEW

**Comment by zulkhair** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #591** <a href="https://app.graphite.dev/github/pr/Argus-Labs/world-engine/591?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/Argus-Labs/world-engine/591?utm_source=stack-comment).

**Review by namrapatel — COMMENTED** [review]
Maybe I'm mistaken about this ticket but I thought WORLD-726 is about reading an allowlist of/off env var in `nakama` and enabling the allowlist via `InitAllowlist` based on that because I don't think that check exists currently?

UPDATE: Nevermind, I misunderstood something! ^

**Comment by technicallyty** [comment]
> Maybe I'm mistaken about this ticket but I thought WORLD-726 is about reading an allowlist of/off env var in `nakama` and enabling the allowlist via `InitAllowlist` based on that because I don't think that check exists currently?

the user sets values in the TOML, and then that TOML gets parsed, and the proper env variables are set.

**Review by namrapatel — APPROVED** [review]

**Comment by zulkhair** [comment]
### Merge activity

* **Feb 12, 2:24 PM EST**: @zulkhair merged this pull request with [Graphite](https://app.graphite.dev/github/pr/Argus-Labs/world-engine/591).

**Pull request merged**
