### PR TITLE
feat(cardinal): add field information to components in /debug/world endpoint

### PR DESCRIPTION
**Pull request by zulkhair**
Closes: WORLD-XXX

## Overview

Add field information to components on `/debug/world` endpoint

## Brief Changelog

- modify response from array of string to array of object contains :
 -- component name
 -- field information

## Testing and Verifying

- Adjust unit test
- Test run and got this response
```
{
    "components": [
        {
            "name": "SignerComponent",
            "fields": {
                "AuthorizedAddresses": "[]string",
                "PersonaTag": "string",
                "SignerAddress": "string"
            }
        },
        {
            "name": "Playersssss",
            "fields": {
                "Nickname": "string"
            }
        },
        {
            "name": "asdsssssasd",
            "fields": {
                "HP": "int"
            }
        }
    ],
    "messages": [
        {
            "name": "create-player",
            "fields": {
                "Nickname": "string"
            }
        },
        {
            "name": "attack-player",
            "fields": {
                "TargetNickname": "string"
            }
        },
        {
            "name": "create-persona",
            "fields": {
                "PersonaTag": "string",
                "SignerAddress": "string"
            }
        },
        {
            "name": "authorize-persona-address",
            "fields": {
                "Address": "string"
            }
        }
    ],
    "queries": [
        {
            "name": "signer",
            "fields": {
                "PersonaTag": "string",
                "Tick": "uint64"
            }
        },
        {
            "name": "state",
            "fields": {}
        },
        {
            "name": "cql",
            "fields": {
                "CQL": "string"
            }
        },
        {
            "name": "list",
            "fields": {
                "StartTick": "uint64"
            }
        },
        {
            "name": "player-health",
            "fields": {
                "Nickname": "string"
            }
        }
    ]
}
```

### CODE REVIEW

**Comment by zulkhair** [comment]
Current dependencies on/for this PR:
* **#646** <a href="https://app.graphite.dev/github/pr/Argus-Labs/world-engine/646?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/Argus-Labs/world-engine/646?utm_source=stack-comment).

**Review by rmrt1n — APPROVED** [review]

**Comment by technicallyty** [comment]
one of the fields shows like this:  `"AuthorizedAddresses": ""`

i think that should be `[]string`.

**Comment by zulkhair** [comment]
checking..

**Comment by zulkhair** [comment]
> one of the fields shows like this:  `"AuthorizedAddresses": ""`
> 
> i think that should be `[]string`. 

Updated.

Changed `field.Type.Name()` to `field.Type.String()` this will return the correct type name for []string and other non-defined types.

**Review by smsunarto — APPROVED** [review]

**Review by smsunarto — CHANGES_REQUESTED** [review]
on second thought, can we move this to `/world` to avoid confusion with `/query/debug/...`

**Comment by smsunarto** [comment]
@zulkhair tests failing.

**Comment by zulkhair** [comment]
> @zulkhair tests failing.

fixed failing test by restacked from main

**Review by smsunarto — APPROVED** [review]

**Pull request merged**
