### PR TITLE
fix(e2e): clean all containers at the end of e2e test rounds

### PR DESCRIPTION
**Pull request by namrapatel**
Closes: WORLD-928

## Overview

This is a simple change that uses `docker compose down -v` to shutdown all the containers at the end of each nakama e2e test run and delete their volumes. This means each new run will start with clean state but also will not require any image redownloading.

### CODE REVIEW

**Review by pyrofolium — APPROVED** [review]
lgtm

**Comment by namrapatel** [comment]
Moving back to draft because I noticed that redis and cockroach db are not being shutdown and as a result their volumes are still alive. Needs more debugging, none of the commands are working to shut them down.

**Comment by pyrofolium** [comment]
> Moving back to draft because I noticed that redis and cockroach db are not being shutdown and as a result their volumes are still alive. Needs more debugging, none of the commands are working to shut them down.

You can try `docker compose down --volumes -v`

**Review by technicallyty — APPROVED** [review]
gg

**Pull request merged**
