### PR TITLE
docs(cardinal): use {custom-group} instead of 'game' in query/tx endpoints

### PR DESCRIPTION
**Pull request by rmrt1n**
Closes: WORLD-1039

## Overview
Since the message/query group is variable (through `WithCustomMessageGroup`/`WithCustomQueryGroup`), the swagger docs should show this.

## Testing and Verifying
Manual verification

### CODE REVIEW

**Comment by rmrt1n** [comment]
* **#728** <a href="https://app.graphite.dev/github/pr/Argus-Labs/world-engine/728?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rmrt1n and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by technicallyty — COMMENTED** [review]
the `server/docs` dir is all generated, right? you just edited the query.go and tx.go?

**Comment by rmrt1n** [comment]
> the `server/docs` dir is all generated, right? you just edited the query.go and tx.go?

yep, generated using `make swagger`

**Review by technicallyty — APPROVED** [review]
lgtm

**Pull request merged**
