### PR TITLE
chore: remove CODEOWNERS

### PR DESCRIPTION
**Pull request by smsunarto**
Closes: WORLD-XXX

## Overview

I propose we remove CODEOWNERS that assigns everyone/anyone to review a PR. I don't think this is working for the following reason:
The current process makes PR review slower
There is ambiguity on who is responsible for reviewing a certain PR when everyone thinks "oh its fine someone else will review the PR". In reality, everyone thought the same thing, so no PR gets reviewed.
It's very spammy on github notifs, which creates tendency for people to ignore GH notifications altogether -> making PR review slower.
The current process implies that anyone's PR review is ok, resulting with PRs getting merged with low quality reviews (i.e. feature PRs getting merged despite not fulfilling the feature requirement, implementations ignoring existing established code patterns, etc).
After parsing through PR approval history, it's clear to me that there is tendency for those who doesn't have much context/understanding/involvement of a certain part of the codebase to just LGTM changes until someone who is more involved in that part of the codebase and has more opinion of the design choice rejects the PR for various valid reasons.
Proposed new PR review process:
Each PR should be reviewed by 2 people (recommended) or 1 person (minimum)
If 2 person:
1 reviewer should be the person who is directly involved with the part of the codebase modified. The Github PR UI will automatically suggest this on the "Reviewers" section on the right sidebar.
1 reviewer should be a person who is deeply familiar with the feature requirement/proposed the task OR any relevant senior engineer.
If 1 person:
This should generally be avoided unless the PR is really basic (i.e. config, ci, nits, etc)
1 reviewer should be the person who is directly involved with the part of the codebase modified.

### CODE REVIEW

**Comment by smsunarto** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #611** <a href="https://app.graphite.dev/github/pr/Argus-Labs/world-engine/611?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/Argus-Labs/world-engine/611?utm_source=stack-comment).

**Comment by technicallyty** [comment]
whats the reason for this? did you find another way to make architects the default reviewer?

**Review by technicallyty — APPROVED** [review]

**Review by namrapatel — APPROVED** [review]
This seems good, but just to be sure we still have a formal GitHub setting where we require 1-2 reviewers right? I think removing that would be a no-go

**Comment by smsunarto** [comment]
> This seems good, but just to be sure we still have a formal GitHub setting where we require 1-2 reviewers right? I think removing that would be a no-go 

Yes, no change on that.

**Pull request merged**
