### PR TITLE
feat(cardinal): add component id & name in DebugState response

### PR DESCRIPTION
**Pull request by rmrt1n**
Closes: WORLD-875

## Overview

Cardinal editor needs the component name to show to the users & the ID to be used for filtering/grouping (although this can also be accomplished using only the name).

## Brief Changelog
original response:
```json
{
    "id": 1,
    "components": [
        {
            "nickname": "CoolMage"
        }
    ]
}
```
~new response:~
```json
{
    "id": 1,
    "components": [
        {
            "id": 2,
            "name": "Player",
            "component": {
              "nickname": "CoolMage"
            }
        }
    ]
}
```

*edit: new response:
```json
{
    "id": 1,
    "components": {
        "Player": {
	     "nickname": "CoolMage"
        }
     }
}
```

## Testing and Verifying
updated unit test to check for the new response fields

### CODE REVIEW

**Comment by rmrt1n** [comment]
Current dependencies on/for this PR:
* **#627** <a href="https://app.graphite.dev/github/pr/Argus-Labs/world-engine/627?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/Argus-Labs/world-engine/627?utm_source=stack-comment).

**Review by technicallyty — APPROVED** [review]
LGTM

**Review by smsunarto — CHANGES_REQUESTED** [review]
i'd prefer the schema to be something like this instead

```
{
    "id": 1,
    "components": {
        "Player": {
	        "nickname": "CoolMage"
        }
		}
}
```

**Review by technicallyty — APPROVED** [review]
lgtm

**Review by smsunarto — APPROVED** [review]

**Pull request merged**
