### PR TITLE
feat(cardinal): golang upgrade to 1.22

### PR DESCRIPTION
**Pull request by pyrofolium**
Closes: WORLD-889

Looks simple but this was a bit harry to get working so I'll save the for loop stuff for another PR. 

Everything was upgraded to 1.22 except for `relay/nakama`. 

@technicallyty I changed stuff in rift and evm but am unable to do a thorough check on these. Can you verify?

### CODE REVIEW

**Comment by technicallyty** [comment]
looks fine to me - also, we can do `GOWORK=off go mod vendor` if you want to avoid vendoring the entire workspace

**Comment by pyrofolium** [comment]
> looks fine to me - also, we can do `GOWORK=off go mod vendor` if you want to avoid vendoring the entire workspace

Please approve if it's everything else looks good. I'll try that suggestion above ^^

**Review by technicallyty — APPROVED** [review]
LGTM, not sure what codecov is complaining abt tho

**Comment by pyrofolium** [comment]
> LGTM, not sure what codecov is complaining abt tho

It has something to do with relay/nakama. That's the only thing I didn't upgrade to 1.22. Gonna ask @heronimus to help, he may know more.

**Comment by pyrofolium** [comment]
Update: I reran the CI and it worked. But coverage reporting for relay has been removed.

**Pull request merged**
